name: Check Git Commits Weekly Cronjob

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Commits
      run: curl https://workfun.vika.ltd/check-git-commits-weeklyxxx
