name: Check Git Commits Weekly Cronjob

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Commits
      run: curl https://workfun.vika.ltd/check-git-commits-weekly  
